<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="XEN-769" name="Google Test" tests="8" failures="6" timestamp="12 May 2016 11:44:51 GMT" time="37.403" errors="0">
  <testcase name="googleSearchVerifyTextTestq" time="12.475" classname="com.xavient.framework.WebApplicationSuite.googleSearchTest"/>
  <testcase name="googleSearchVerifyTextTestq" time="0.024" classname="com.xavient.framework.WebApplicationSuite.googleSearchTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.xavient.framework.util.Xls_Reader.getRowCount(Xls_Reader.java:48)
	at com.xavient.framework.util.Utility.isTestCaseRunnable(Utility.java:85)
	at com.xavient.framework.util.Utility.validateTestExecution(Utility.java:113)
	at com.xavient.framework.WebApplicationSuite.googleSearchTest.googleSearchVerifyTextTestq(googleSearchTest.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- googleSearchVerifyTextTestq -->
  <testcase name="googleSearchVerifyTextTestq" time="0.053" classname="com.xavient.framework.WebApplicationSuite.googleSearchTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.xavient.framework.util.Xls_Reader.getRowCount(Xls_Reader.java:48)
	at com.xavient.framework.util.Utility.isTestCaseRunnable(Utility.java:85)
	at com.xavient.framework.util.Utility.validateTestExecution(Utility.java:113)
	at com.xavient.framework.WebApplicationSuite.googleSearchTest.googleSearchVerifyTextTestq(googleSearchTest.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- googleSearchVerifyTextTestq -->
  <testcase name="googleSearchTest" time="31.926" classname="com.xavient.framework.WebApplicationSuite.googleSearchTest"/>
  <testcase name="googleSearchTest" time="0.015" classname="com.xavient.framework.WebApplicationSuite.googleSearchTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.xavient.framework.util.Xls_Reader.getRowCount(Xls_Reader.java:48)
	at com.xavient.framework.util.Utility.isTestCaseRunnable(Utility.java:85)
	at com.xavient.framework.util.Utility.validateTestExecution(Utility.java:113)
	at com.xavient.framework.WebApplicationSuite.googleSearchTest.googleSearchTest(googleSearchTest.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- googleSearchTest -->
  <testcase name="googleSearchVerifyTextTest" time="36.747" classname="com.xavient.framework.WebApplicationSuite.googleSearchTest">
    <failure type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at com.xavient.framework.WebApplicationSuite.googleSearchTest.googleSearchVerifyTextTest(googleSearchTest.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'XEN-769', ip: '10.1.249.94', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_77'
Driver info: driver.version: FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=43.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 5610945f-45e6-43f8-b97d-84e51cbd0e71
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:701)
	at org.openqa.selenium.firefox.FirefoxDriver.getScreenshotAs(FirefoxDriver.java:341)
	... 19 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:7057 [/127.0.0.1] failed: Connection refused: connect
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:140)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.execute(NewProfileExtensionConnection.java:160)
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.execute(FirefoxDriver.java:380)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 24 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:117)
	... 39 more
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- googleSearchVerifyTextTest -->
  <testcase name="googleSearchVerifyTextTest" time="0.078" classname="com.xavient.framework.WebApplicationSuite.googleSearchTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.xavient.framework.util.Xls_Reader.getRowCount(Xls_Reader.java:48)
	at com.xavient.framework.util.Utility.isTestCaseRunnable(Utility.java:85)
	at com.xavient.framework.util.Utility.validateTestExecution(Utility.java:113)
	at com.xavient.framework.WebApplicationSuite.googleSearchTest.googleSearchVerifyTextTest(googleSearchTest.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- googleSearchVerifyTextTest -->
  <testcase name="googleSearchVerifyTextTest" time="0.048" classname="com.xavient.framework.WebApplicationSuite.googleSearchTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.xavient.framework.util.Xls_Reader.getRowCount(Xls_Reader.java:48)
	at com.xavient.framework.util.Utility.isTestCaseRunnable(Utility.java:85)
	at com.xavient.framework.util.Utility.validateTestExecution(Utility.java:113)
	at com.xavient.framework.WebApplicationSuite.googleSearchTest.googleSearchVerifyTextTest(googleSearchTest.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- googleSearchVerifyTextTest -->
</testsuite> <!-- Google Test -->
